Fix: Hold action with multiple bindings (case 1239551)
Unity-Technologies/InputSystem pull request #1197
Opened 2020-08-24 16:07 UTC by karljj1

Fixed Action with multiple bindings becoming unresponsive after a Hold interaction was performed. ([case 1239551](https://issuetracker.unity3d.com/issues/input-system-hold-interaction-makes-an-input-action-unresponsive-when-2-or-more-binding-are-attached-to-the-same-input-action))

When we copy the state over we need to do so before we copy the flags as we don't want the Have Magnitude flag.

Includes Test which fails before the fix and passes afterwards. I commited the test first so you can run the tests against it to verify if you wish.

2020-08-24 20:23 UTC, Rene-Damm requested changes

2020-08-24 20:23 UTC, Rene-Damm commented on Assets/Tests/InputSystem/CoreTests_Actions_Interactions.cs
> +        //var gamepad = InputSystem.AddDevice<Gamepad>();
Plz remove

2020-08-24 20:23 UTC, Rene-Damm commented on Assets/Tests/InputSystem/CoreTests_Actions_Interactions.cs
> +    void TestHoldInteraction(InputAction action, ButtonControl button)
Please no methods like this. Makes it hard to understand the tests. Would actually recommend simply folding `_WithMultipleBindings` into the other test.

2020-08-24 20:23 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/InputSystem/Actions/InputActionState.cs
> +            newState.flags = actionState->flags; // Preserve flags.
Please add comment about the dependency here.

2020-09-01 09:29 UTC, karljj1 commented on Packages/com.unity.inputsystem/InputSystem/Actions/InputActionState.cs
>              if (!newState.haveMagnitude)
@Rene-Damm This change is causing several tests to fail.
They all have messages like this
_InvalidOperationException: Cannot query value of control '/VirtualMouse/scroll' before 'VirtualMouse' has been added to system!'_

Should I check if they have been added to the system before calling ComputeMagnitude? How can i do this?

2020-09-01 16:16 UTC, midopooler approved these changes
LGTM but can't comment on what is causing several tests to fail.

2020-10-07 09:14 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/InputSystem/Actions/InputActionState.cs
> +            // the `HaveMagnitude` flag which would give us an incorrect magnitude value. (case 1239551)
Now I notice this is actually incorrect this way, too. It computes the magnitude which sets the `HaveMagnitude` flag on `newState`. Which may then get nuked by the copying over of flags.

I'll go fix it and merge the PR.

2020-10-07 11:46 UTC, merged