Miscellaneous changes for XR devices
Unity-Technologies/InputSystem pull request #122
Opened 2018-05-22 19:31 UTC by StayTalm

-Added preliminary docs, all except device-specifics
-Added a new version of XRInput interface, that handles android and non-android layouts the same (+ back compat)
-Added tests for new button format
-Updated naming of all XR inputs to be in the past tense, as well as complete
-XR Test scenes and utilities from @jackpr-unity 
-Changed UNITY_UWP defines to UNITY_WSA
-Fixed recurring crashes on multiple editor play-stop sequences

2018-05-22 20:24 UTC, Rene-Damm requested changes

2018-05-22 20:24 UTC, Rene-Damm commented on ProjectSettings/ProjectVersion.txt
> +m_EditorVersion: 2018.3.0a1
Please revert this change. Otherwise users will see downgrade warnings.

2018-05-22 20:24 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/XRSupport.cs
> +        public const string kXRInterfaceMatchingPattern = "^(XRInput)";
`kXRInterfaceMatchAnyVersion`? Took me a moment to realize that "any XRInput interface" seems to mean "any version of the XRInput interface".

2018-05-22 20:24 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/Haptics/SimpleXRRumbleCommand.cs
> +    /// An IOCTL command sent to a device to set it's motor rumble intensity.
IOCTL isn't really a thing on the managed side. It's just called "device command".

2018-05-22 20:24 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/GenericXRDevice.cs
> +        /// Set's this device's motor intensity.
As a general comment, the doc comments here tend to stay on the side of the obvious. The non-obvious isn't really addressed. When does the change take effect? What if the value is outside the range? How often can I call this and will the device respond immediately? Do I need to call this repeatedly to keep it going?

2018-05-22 20:24 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/GenericXRDevice.cs
> +        /// Set's this device's motor intensity.
(Also, other stuff like what happens if I call this while haptics are paused? etc)

2018-05-22 20:24 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/InputSystem/InputSystem.cs
> +#if UNITY_EDITOR || UNITY_STANDALONE || UNITY_WSA
Keep formatting consistent.

2018-05-22 20:24 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/GenericXRDevice.cs
> +        /// </summary>
Continuing re doc comments... like here, for example. What does "This is also tracked via usages on the device." mean.

```
/// <summary>
/// The most recently used XRController that is marked as left hand.
/// </summary>
/// <remarks>
/// Handedness is indicated by usages set on the device. An XRController that contains <see cref="CommonUsages.LeftHand"/> in <see cref="InputControl.usages"/>
/// is considered the left hand controller.
/// </remarks>
```

2018-05-22 20:24 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/GenericXRDevice.cs
> +    /// The base type for all XR handed controllers.  This can help retrieve handed-specific information.
Can help how? Be specific.

2018-05-22 20:24 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/GenericXRDevice.cs
> +            string capabilities = description.capabilities;
Use var.

2018-05-22 20:24 UTC, Rene-Damm commented on ProjectSettings/EditorBuildSettings.asset
> +  m_Scenes: []
Please revert.

2018-05-22 23:00 UTC, StayTalm commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/GenericXRDevice.cs
> +        /// Set's this device's motor intensity.
I put the pause comments on the pause documentation, but I'm updating the rest to include the non-obvious.

2018-05-23 18:09 UTC, StayTalm commented
@Rene-Damm The new changeset: 
425fff8
Should cover all requested changes :)

2018-05-23 18:09 UTC, StayTalm commented
The new changeset: 425fff8
Should have all the requested changes.

2018-05-23 19:26 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/GenericXRDevice.cs
> +        /// <remarks>If there is no left hand connected, this will be null. This also matches any currently tracked device that contains the 'LeftHand' device usage.</remarks>
Recommend linking to specific APIs whenever possible. No API docs are more frustrating than Apple's where the guy is clearly writing about some API existing elsewhere but there's no link.

2018-05-23 19:29 UTC, merged