fixes sizeof calculation in querycanruninbackground IOCTL command.
Unity-Technologies/InputSystem pull request #1233
Opened 2020-10-28 06:26 UTC by mattdatwork

fixes sizeof calculation in querycanruninbackground IOCTL command.

2020-10-28 07:47 UTC, jechter approved these changes

2020-10-28 10:52 UTC, Rene-Damm requested changes
Test and CHANGELOG or it didn't happen :)

2020-10-28 17:06 UTC, mattdatwork commented
> Test and CHANGELOG or it didn't happen :)

not sure how we can add a test for this in any sort of generic way. I can add a test that checks to see if the QCRIB is the right size, but thats limited utility?

2020-10-29 14:12 UTC, Rene-Damm commented
Added test and CHANGELOG.

2020-12-02 14:19 UTC, merged