Add XboxOne/DualShock layouts for Android
Unity-Technologies/InputSystem pull request #1255
Opened 2021-01-05 15:11 UTC by rytis-buz

Added DualShock4GamepadAndroid and XboxOneGamepadAndroid layouts that derive from DualShockGamepad and XInputController respectively instead of deriving from AndroidGamepad
Fixed Right stick to use AXIS.Z and AXIS.RZ
Fixed triggers to always use Axis.Gas and Axis.Brake
Moved AndroidGamepadWithDpadButtons and AndroidGamepadWithDpadAxes from Json definition to class definition

2021-01-05 15:14 UTC, rytis-buz commented on Packages/com.unity.inputsystem/InputSystem/Plugins/Android/AndroidGameController.cs
> +        [InputControl(name = "leftTrigger", offset = (uint)AndroidAxis.Brake * sizeof(float) + kAxisOffset, parameters = "clamp=1,clampMin=0,clampMax=1.0", variants = kVariantGamepad)]
This clamping for triggers is questionable. There is a test that sets -1 and expects 0 as a result with a comment "Check if normalization works correctly". Clamping seemed to be the way to achieve that

2021-01-11 09:37 UTC, todi1856 commented
Could you add QA, since this is a sensitive change

2021-01-11 09:40 UTC, todi1856 commented
Missing entries in CHANGELOG

2021-01-12 09:20 UTC, todi1856 requested changes
Looks good, tested myself Dualschock on Google Pixel 2 XL with Android 11, works fine.

Please add QA, after QA approves, I'll approve too

2021-01-12 09:20 UTC, todi1856 commented on Packages/com.unity.inputsystem/InputSystem/Plugins/Android/AndroidGameController.cs
> +        [InputControl(name = "rightStick/up", offset = ((uint)AndroidAxis.Rz - (uint)AndroidAxis.Z) * sizeof(float), variants = kVariantGamepad,
no change here ? can you revert, same for  rightStick

2021-01-12 09:20 UTC, todi1856 commented on Packages/com.unity.inputsystem/InputSystem/Plugins/Android/AndroidGameController.cs
> +    ///  Right Stick -> AXIS_Z (11) / AXIS_RZ(14)
So it seems, this comment is no longer relevent, as mapping matches the comment scope above next to /// Most of the gamepads: 

if so, can you delete this scope, and add Xbox Controller in the list above (after Sony Interactive Entertainment Wireless), also could you please add device name and android os version next to the device just as an additional info

2021-01-12 09:20 UTC, todi1856 requested changes
Please add entries to CHANGELOG

2021-01-12 21:30 UTC, todi1856 approved these changes

2021-01-18 08:33 UTC, renaldasrep commented
Sorry it's taking a while, we're trying to get a hold of required controllers, should be able to have them at hand by the end of the week

2021-01-28 10:18 UTC, renaldasrep approved these changes
Tested on multiple android devices using DualShock 4 and the Xbox Series X controller
No issues found apart DualShock 4 working pretty randomly on Android 8, but it is documented now that it is not officially supported (notes added in this PR)

2021-03-09 09:25 UTC, rytis-buz commented
@Rene-Damm The PR has been open for 2 months and now have conflicts. Can we move forward with it?

2021-07-15 14:27 UTC, ekcoh commented
@rytis-buz @todi1856 @renaldasrep sorry for the late follow-up on this PR but we (@andrew-oc, @ekcoh)  have looked through it now and would be happy to merge it to develop. We did some minor modifications on our end and just want to check that yo uare onboard with this happening now before we merge.

2021-07-15 19:26 UTC, todi1856 commented
looks good

2021-07-19 06:47 UTC, rytis-buz commented
Looks good to me

2021-07-19 07:57 UTC, merged