Setting default input actions asset in InputSystemUIInputModule (fixes 1323566)
Unity-Technologies/InputSystem pull request #1317
Opened 2021-04-15 13:49 UTC by jimon

### Description

When adding ui module with `AddComponent<InputSystemUIInputModule>` in `Awake` of some script present in the scene, deserialization of default references of ui module happens after `OnEnable` is called. Which makes `InputSystemUIInputModule` not work correctly, e.g. setting `module.actionsAsset = defaultReference` would be a no-op even if module went through `Awake`/`OnEnable` with `m_ActionsAsset` being `null`

### Changes made

If we detect that no asset was set in hidden serialized properties, provide a default asset instead.

### Notes

This is not possible to test from unit test. The behavior is only reproducible when pressing play button in editor, as part of entering playmode we load the scene and call `Awake` on everything, but editor is not in play loop yet, hence why setting default refences is still enabled at that point. Unit tests run in play mode instead.

### Checklist

- [X] Changelog entry added.
- [X] Tests added/changed, if applicable.

2021-04-16 12:45 UTC, andrew-oc approved these changes

2021-04-16 12:45 UTC, andrew-oc commented on Packages/com.unity.inputsystem/InputSystem/Plugins/UI/InputSystemUIInputModule.cs
> +            m_PointAction = InputActionReference.Create(defaultActions.@UI.Point);
What's with the verbatims?

2021-04-23 14:39 UTC, andrew-oc requested changes

2021-04-23 14:39 UTC, andrew-oc commented on Packages/com.unity.inputsystem/InputSystem/Plugins/UI/InputSystemUIInputModule.cs
> +        /// Useful for creating <see cref="InputSystemUIInputModule"/> in runtime.
"...*at* runtime"

2021-04-29 08:26 UTC, jimon commented on Packages/com.unity.inputsystem/InputSystem/Plugins/UI/InputSystemUIInputModule.cs
> +            m_PointAction = InputActionReference.Create(defaultActions.@UI.Point);
N/A anymore

2021-04-29 08:26 UTC, jimon commented on Packages/com.unity.inputsystem/InputSystem/Plugins/UI/InputSystemUIInputModule.cs
> +        /// Useful for creating <see cref="InputSystemUIInputModule"/> in runtime.
fixed

2021-04-29 09:33 UTC, andrew-oc approved these changes

2021-04-29 09:53 UTC, merged