Few touch tests
Unity-Technologies/InputSystem pull request #148
Opened 2018-06-19 11:55 UTC by todi1856

Added two tests which are currently failing, so we can decide what to do:
* Devices_TouchesWithSameIdDontGetStuck
  two touches with same id happen during one frame, because of that touch is stuck in Stationary phase.
  Such behavior happened on Android, where it was legal for touches to have same id, when they happen one after another
  If we don't allow such behavior, can we add an exception or error in Development build?

* Devices_TouchesWithWrongTimestampCorrectlyRecognized
  Touch event which comes timestamp which is less than previous event is implicitly ignored. Happened on android due precision issues... Again, can input system in development build throw a warning that event is ignored?

2018-06-20 22:28 UTC, Rene-Damm requested changes

2018-06-20 22:28 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/Tests/InputSystem/CoreTests_Devices.cs
> +    public void Devices_TouchesWithSameIdDontGetStuck()
Please name TODO_Devices_TouchesWithSameIdDontGetStuck. Regular tests should be green.

2018-06-20 22:28 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/Tests/InputSystem/CoreTests_Devices.cs
> +    public void Devices_TouchesWithWrongTimestampCorrectlyRecognized()
Same here. Prefix with TODO_.

2018-06-20 22:29 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/Tests/InputSystem/CoreTests_Devices.cs
> +    public void Devices_TouchesWithWrongTimestampCorrectlyRecognized()
Alternatively we could also adopt a FIXME_ prefix for tests that isolate known bugs (unlike the more general "this still needs to be implement" kind of thing that the TODO_ tests generally revolve around).

2018-07-11 11:52 UTC, todi1856 commented
@Rene-Damm prefixed with FIXME_

2018-07-17 11:20 UTC, todi1856 commented
Closing for now, found more issues with gamepad

2018-07-17 11:20 UTC, closed without merging