Fixing XBox One controller on macOS
Unity-Technologies/InputSystem pull request #1515
Opened 2022-03-10 14:10 UTC by jimon

### Description

Xbox gamepad is much more sophisticated than what we currently have in code.

It sends a variety of different reports, one of which is part of a handshake, and it doesn't map to what we currently have in the struct.

### Changes made

A hot fix to ignore all packets but ones that we know contain control reports (0x01 and 0x20).

2022-03-10 14:10 UTC, unity-cla-assistant commented
[![CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/pull/badge/not_signed)](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/InputSystem?pullRequest=1515) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/InputSystem?pullRequest=1515) before we can accept your contribution.<br/><hr/>**Dmytro Ivanov** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/InputSystem?pullRequest=1515) it.</sub>

2022-03-11 10:48 UTC, ekcoh requested changes
If it works :) Would be good to get the FB/issue number in for tracking

2022-03-11 10:48 UTC, ekcoh commented on Packages/com.unity.inputsystem/CHANGELOG.md
> +- Xbox One reporting invalid controls before first actuation of any control (case TBA).
Do we have a FogBugz case for this? Otherwise we should create one to references, I guess the TBA reflects this will be added?

2022-03-11 10:48 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XInput/XboxGamepadMacOS.cs
> +            return (stateEvent->stateSizeInBytes == 0) || ((stateEvent->stateSizeInBytes > 0) && (binaryData[0] == 0x01 || binaryData[0] == 0x20));
Trial and error or seen "similar" approaches to filter reports?

2022-03-17 10:50 UTC, jimon commented
This is completely wrong fix for it, closing.

2022-03-17 10:50 UTC, closed without merging