Add Tracking State support to TrackedPoseDriver
Unity-Technologies/InputSystem pull request #1594
Opened 2022-10-11 06:59 UTC by chris-massie

### Description

This adds support for constraining the `TrackedPoseDriver` to only update the Transform if the XR device reports the position and rotation values are valid. An XR device may indicate that the position and/or rotation values are not valid if tracking is lost, so users should typically not update the Transform to match garbage data and instead keep it unchanged.

This is a replacement for the old PR https://github.com/Unity-Technologies/InputSystem/pull/1481 which had many open comments.

### Changes made

Added `public bool ignoreTrackingState` and `public InputActionProperty trackingStateInput` properties to `TrackedPoseDriver`, which requires a bump in minor version. The `Reset` method also applies expected control types of the input actions for ease of configuration by users.

### Notes

The default value of `ignoreTrackingState = true` keeps the existing functionality where the updating of the Transform is unconstrained by Tracking State.

### Checklist

Before review:

- [x] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - FogBugz ticket attached, example `([case %number%](https://issuetracker.unity3d.com/issues/...))`.
    - FogBugz is marked as "Resolved" with *next* release version correctly set.
- [x] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [x] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

2022-10-14 23:25 UTC, vrdave-unity requested changes
Looks pretty straight-forward. I had a couple of nitpicks with potential null ref cases.

2022-10-14 23:25 UTC, vrdave-unity commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +                return;
There may be a scenario where a user externally sets `trackingStateInput = null`
```suggestion
            if (m_TrackingStateInput == null)
                return;

            var action = m_TrackingStateInput.action;
            if (action == null)
                return;
```

2022-10-14 23:25 UTC, vrdave-unity commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +                return;
```suggestion
            if (!m_TrackingStateBound || m_TrackingStateInput == null)
                return;
```

2022-10-14 23:25 UTC, vrdave-unity commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +            var actionMap = trackingStateAction.GetOrCreateActionMap();
If we cannot assume m_TrackingStateInput is properly set, we need some extra null checks here unfortunately...
```suggestion
            if (m_TrackingStateInput != null && m_TrackingStateInput.action != null && !trackingStateAction.enabled)
            {
                // Treat a disabled action as the default None value for the ReadValue call
                m_CurrentTrackingState = TrackingStates.None;
                return;
            }
           
            if (m_TrackingStateInput == null || m_TrackingStateInput.action == null || trackingStateAction.m_BindingsCount == 0)
            {
                // Treat an Input Action Reference with no reference the same as
                // an enabled Input Action with no authored bindings, and allow driving the Transform pose.
                m_CurrentTrackingState = TrackingStates.Position | TrackingStates.Rotation;
                return;
            }

            // Grab state.
            var trackingStateAction = m_TrackingStateInput.action;
            var actionMap = trackingStateAction.GetOrCreateActionMap();
```

2022-10-17 20:37 UTC, vrdave-unity approved these changes

2022-10-17 20:40 UTC, unity-andrewc approved these changes
I didn't have anything to add beyond Dave's feedback

2022-11-17 13:06 UTC, jimon commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +            // Get list of resolved controls to determine if a device actually has tracking state.
Do I understand that this logic is to check if there is any active binding on the action @chris-massie ?

2022-11-17 13:19 UTC, jimon commented
Gonna rebase on latest develop to get up-to-date CI

2022-11-17 14:25 UTC, jimon commented
CI failures are expected and unrelated to this PR

2022-11-17 14:26 UTC, merged