First pass on querying controls in basic api
Unity-Technologies/InputSystem pull request #1595
Opened 2022-10-18 16:20 UTC by jimon

Still think we should try method overloads from https://github.com/Unity-Technologies/InputSystem/issues/1559#issuecomment-1248152830

2022-10-18 16:49 UTC, jamesmcgill approved these changes
nice!

2022-10-18 16:49 UTC, jamesmcgill commented on Packages/com.unity.inputsystem/InputSystem/API/Input.cs
> +            // WHAT THE FCK!? or .. can we do better?
A minor improvement (for enums in the keyboard range at least) might be to move the key mapping out of here and into a dedicated function. Eg.
`
if (input < Inputs.Key_MAX) {
    return Keyboard.current != null ? Keyboard.current[KEYMAP_FUN(input)] : null;
}
`

2022-10-18 16:49 UTC, jamesmcgill commented on Packages/com.unity.inputsystem/InputSystem/API/Input.cs
>          public static bool IsControlUp(Inputs input)
Still got confused by the naming here (but maybe just me) as it doesn't imply it's temporal in nature.
I.e. this is going to return false the majority of the time, even when keys are not being pressed (and are 'up').

2022-10-19 09:39 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/API/Input.cs
> +            // WHAT THE FCK!? or .. can we do better?
Agree with single null check and early return on that.

But why arent we just setting the enum values to the enum value of the underlying mapped type? If you want a translation table for some reason thats fine, but maybe generate it in that case? Or put it in an extension method for the enum and return just value (and then translations can be added there on a need basis)?

2022-10-19 11:40 UTC, andrew-oc requested changes
Xmldoc comments should be updated for public methods as part of this PR

2022-10-20 12:01 UTC, merged