Update Input Test
Unity-Technologies/InputSystem pull request #160
Opened 2018-07-02 21:25 UTC by JiaUnity

- Bug Fix
- Add shortcuts to switch between tests for different inputs (ctrl + [num])
- More Information UI and shortcut to expand it (ctrl + i)

2018-07-04 08:40 UTC, Rene-Damm requested changes

2018-07-04 08:40 UTC, Rene-Damm commented on Assets/QA/Input_Test/Created by @jia.txt
> +   WARNING: this could affect other tests in the same project. Be sure to make backup before replacing.
I suggest putting the asset into the repo (probably in some toplevel folder; e.g. "QA/InputManager.asset" or something). Even better would be to not rely on manual procedures for these things but rather have menu items (e.g. a "QA" toplevel menu) that drive various QA automation tasks (such as building a player with the QA scenes without having to modify the global scene list).

2018-07-04 08:40 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/InputSystem/Actions/Modifiers.meta
> +  assetBundleVariant:
Please remove this file. There's no Modifiers folder anymore.

2018-07-10 00:15 UTC, JiaUnity commented
The issues should be fixed.

2018-07-18 18:08 UTC, merged