Fix device disconnects being missed on console platforms while running in the background
Unity-Technologies/InputSystem pull request #1648
Opened 2023-02-17 16:56 UTC by andrew-oc

### Description

Certain platforms ignore the runInBackground flag. If a device disconnect event occurs while the app is in the background on one of those platforms, the input system will discard the event, and the device instance will stay in memory.

### Changes made

Forced the input system to ignore the runInBackground flag in managed code on the troublesome platforms.

### Checklist

Before review:

- [x] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - FogBugz ticket attached, example `([case %number%](https://issuetracker.unity3d.com/issues/...))`.
    - FogBugz is marked as "Resolved" with *next* release version correctly set.

2023-03-14 16:06 UTC, jfreire-unity approved these changes

2023-03-14 16:06 UTC, jfreire-unity commented on Packages/com.unity.inputsystem/InputSystem/NativeInputRuntime.cs
> +        Application.platform == RuntimePlatform.GameCoreXboxSeries;
Nice for adding all these console platforms 👍 
Just to have more clarity on this: 
- Did you (or someone) validate on all of these platforms?
- Also, the ticket talks mostly about PS5 and package version 1.3.0. I assume this was probably already fixed in 1.5.0 for PS5, as it was already a platform that run in the background before this PR?
- This PR only adds the PS4 and Xbox console platform checks, which are also commented on the UUM issue, right?

2023-03-17 14:51 UTC, MattWUnity3d requested changes

2023-03-17 14:51 UTC, MattWUnity3d commented on Packages/com.unity.inputsystem/InputSystem/NativeInputRuntime.cs
> +        Application.platform == RuntimePlatform.GameCoreXboxOne ||
Adding NDAed platform references into the public package is not OK. There are specific input system packages for all of these platforms where platform specific functionality should go.
The input system package is the go to example of how to correctly implement supporting closed platforms, and this is absolutely not the way to do it.

2023-03-17 18:00 UTC, DTetlow commented on Packages/com.unity.inputsystem/InputSystem/NativeInputRuntime.cs
> +        Application.platform == RuntimePlatform.GameCoreXboxOne ||
Matt is absolutely correct, please take this PR down and come and talk to the respective platform teams on how to implement this.

2023-03-20 09:05 UTC, closed without merging