CHANGE: Add automated testing setup for InputForUI
Unity-Technologies/InputSystem pull request #1680
Opened 2023-05-19 15:06 UTC by jfreire-unity

### Description

Adds the test setup for the InputSystemProvider that is used on the 2023.2+ InputForUI module.

### Changes made

Sets up the Unity project to test the InputForUI module with the InputSystemProvider implementation.
Adds a basic test with a mouse to validate that the test setup is working and that events are being dispatched.

### Notes

**This depends on #1679 and should not be merged before** 

### Checklist

Before review:

- [ ] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - FogBugz ticket attached, example `([case %number%](https://issuetracker.unity3d.com/issues/...))`.
    - FogBugz is marked as "Resolved" with *next* release version correctly set.
- [x] Tests added/changed, if applicable.
    - Functional tests : 'Plugins/InputForUITests.cs`

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

2023-05-19 15:22 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/Views/InputActionsTreeViewItem.cs
> +            e.StopPropagation();
Great to see this fix - thank you :)

2023-05-19 15:34 UTC, lyndon-unity approved these changes
Looks like a sensible addition.
Obviously wait for the main provider to land (or merge into that branch)

2023-05-19 15:35 UTC, lyndon-unity commented
That said this is failing tests which are related so it looks like it needs a fix

2023-05-19 15:35 UTC, lyndon-unity requested changes
Tests are failing ATM

error CS0122: 'EventProvider' is inaccessible due to its protection level

2023-05-22 11:08 UTC, jfreire-unity commented
@lyndon-unity Yeah, this PR requires some `trunk` changes to land first.
Currently it's also a Draft PR. Once changes land in `trunk`, I'll re-run the tests and ask again for review.

2023-05-23 13:25 UTC, lyndon-unity approved these changes
Seems reasonable, happy to see test coverage expanding

2023-05-23 13:25 UTC, lyndon-unity commented on Assets/Tests/InputSystem/Plugins/InputForUITests.cs
> +        Move(mouse.position, new Vector2(100f, 0.5f));
Should we be testing a mouse click too here ?

2023-05-24 08:27 UTC, jfreire-unity commented
Changing it back to DRAFT so that it only lands in 1.6.1

2023-05-24 08:28 UTC, jfreire-unity commented
Holding this for after the 1.6.0 release since the `trunk` PR has not landed yet.

2023-05-31 09:18 UTC, merged