NEW: edit actions and bindings properties (ISX-1374)
Unity-Technologies/InputSystem pull request #1691
Opened 2023-06-22 15:15 UTC by ritamerkl

### Description

added the functionality to edit various fields for Actions, Bindings, Composites and Bindings in Composites. 
Includes adding, editing, reordering and deleting of Interactions and Processors. See the Ticket [here]([ISX-1374](https://jira.unity3d.com/browse/ISX-1374)).

### Changes made

added:
- editing properties of Actions, Bindings, Composites
- adding Interactions & Processors
- editing Interactions & Processors
- deleting Interactions & Processors
- reordering Interactions & Processors

### Notes

### Checklist

Before review:

- [] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - FogBugz ticket attached, example `([case %number%](https://issuetracker.unity3d.com/issues/...))`.
    - FogBugz is marked as "Resolved" with *next* release version correctly set.
- [] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

2023-06-22 16:12 UTC, lyndon-unity requested changes
Looks reasonable. I've made a couple of queries so will pause before approving. Answers might mean no changes needed though.

2023-06-22 16:12 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/InputParameterEditor.cs
> +                //only add inputSettingsButton and help box if default is enabled
Not sure this comment adds much value.

I can see the default variable is controlling if the button and help box shows up, but I don't really understand what 'default is enabled' means. I'd suggest either remove the comment or expand to tell me more than the local code.

2023-06-22 16:12 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/InputParameterEditor.cs
> +            private void BlurFloatField(Action onChangedCallback)
Blur was a new event to me and therefore I also struggled with the naming on this. If this could be used in more than one place and isn't float specific could this perhaps be renamed to TriggerChangeCallback or something more action oriented?

2023-06-22 16:12 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/InputParameterEditor.cs
> -                m_HelpBox.visible = m_UseDefaultValue;
I like that these have moved to the setup phase and no longer needs to toggle visibility.

2023-06-22 16:12 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/Resources/InputActionsEditorStyles.uss
> +    background-image: resource('Packages/com.unity.inputsystem/InputSystem/Editor/Icons/d_ChevronUp.png');
The icon seems to have a difference naming convention to the one above without the d_ 
Is there a reason these are inconsistent.

I seem to recall seeing some naming convention in a style guide somewhere but could only find these which didn't seem to help on this specific question
https://docs-style-guide.unity.com/media/images/image-type-guidelines/diagrams#icons
https://unityeditordesignsystem.unity.com/fundamentals/iconography#Overview

2023-06-22 16:12 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/Views/ActionPropertiesView.cs
> +                controlTypeIndex = Math.Clamp(controlTypeIndex, 0, controlTypes.Count - 1);
Is this clamping to default to the zero's element if no match is found ?
Seems reasonable but I for a moment wondered why it was here. Perhaps a comment on the line would help

2023-06-22 16:12 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/Views/NameAndParametersListView.cs
> +            var newElement = new NameAndParameters() { name = name};
Should this initialise the parameters too ?

2023-06-22 16:12 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/Views/NameAndParametersListView.cs
> +            if (!up)
Feels like you should collapse this into one line so you don't set the value twice if up is false. Trivial but if ever used in a loop could be more performant.

var newIndex = up ? index -1 : index +1;

2023-06-22 16:12 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/Views/NameAndParametersListView.cs
> +            var interactionsOrProcessorsList = NameAndParameters.ParseMultiple(m_ListProperty.stringValue).ToArray();
This says ToArray but the variable is named List which is a bit confusing.

2023-06-22 16:12 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/Views/NameAndParametersListView.cs
> +            newIndex = Math.Clamp(newIndex, 0, interactionsOrProcessorsList.Length - 1);
If the interactionsOrProcessorsList is empty this seems it would have an issue with clamping to range 0,-1 and the swap would fail below.

Perhaps this can never happen due to calling this code with always valid values, but an early out might be wise.
Also should we clamp in this case or just early out if the newIndex is out of range ?

2023-06-22 16:12 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/Views/NameAndParametersListView.cs
> +                    onClickUp = () => MoveElement(index, true),
perhaps consider an enum for the second parameter to Move element to make it clearer which is up and which is down. Or given how simple the function is, have a dedicated up and down variation.

2023-06-22 16:12 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/Views/NameAndParametersListView.cs
> +                var index = i;
Why do we have a separate index and i - they seem to be the same.

2023-06-22 16:12 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/Views/PropertiesView.cs
> +using System.Linq;
I always question if we need LINQ as it can be poor performance at times, but I think for the UI work it makes sense to use.

2023-06-22 16:12 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/Views/PropertiesView.cs
> +            if (!string.IsNullOrEmpty(expectedControlType))
When you have a value being set above and then a conditional to update it I always prefer folding these into one to set the value only once.

var data = conditional ? truevalue : falseValue;

2023-06-22 16:12 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/Views/PropertiesView.cs
> +            if (!string.IsNullOrEmpty(expectedControlType))
So here

Type expectedValueType = string.IsNullOrEmpty(expectedControlType) ? null : EditorInputControlLayoutCache.GetValueType(expectedControlType);

2023-06-22 16:12 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/Views/PropertiesView.cs
> +                evt.menu.ClearItems();
For bigger callback content like this I'm tempted to suggest snapping out to a function

2023-06-22 16:12 UTC, lyndon-unity commented on ProjectSettings/MemorySettings.asset
> +%YAML 1.1
Unsure why this file is a new addition - perhaps just never checked in before so probably makes sense.

2023-06-23 10:09 UTC, ritamerkl commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/Views/NameAndParametersListView.cs
> +                var index = i;
we need a local index to save a steady copy of the integer, otherwise we would reference the changing i variable of the loop

2023-06-23 12:54 UTC, ritamerkl commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/Resources/InputActionsEditorStyles.uss
> +    background-image: resource('Packages/com.unity.inputsystem/InputSystem/Editor/Icons/d_ChevronUp.png');
After some research I found out that the d_ prefix is used for dark scheme of the editor. So I adjusted the code accordingly. Thank you for bringing that up.

2023-06-28 07:50 UTC, lyndon-unity approved these changes
Good updates, minor comment added. Generally happy to approve

2023-06-28 07:50 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/Views/NameAndParametersListView.cs
> +            if (interactionsOrProcessors.Length == 0 || newIndex < 0 || newIndex >= interactionsOrProcessors.Length)
Looks good. I think we should probably check oldIndex too
If we never expect this to be out of range we should probably assert so they get flagged.

2023-07-07 08:08 UTC, merged