FIX: save and reset input action asset (ISX-1525, ISX-1483, ISX-1559)
Unity-Technologies/InputSystem pull request #1727
Opened 2023-08-11 13:11 UTC by ritamerkl

### Description

Three tickets around saving/auto-saving and reset the input action asset including a dialog (showing up if no auto-save is enabled and the editor window is closed) are solved in this PR. You can find them here: [ISX-1525](https://jira.unity3d.com/browse/ISX-1525), [ISX-1483](https://jira.unity3d.com/browse/ISX-1483), [ISX-1559](https://jira.unity3d.com/browse/ISX-1559).

### Changes made

fixed:
- reset dialog properly if changes got discarded
added:
- dialog that shows up on closing the editor window and auto-save is disabled 
- dirty asset editor window if auto-save disabled and asset has unsaved changes

### Checklist

Before review:

- [ ] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - FogBugz ticket attached, example `([case %number%](https://issuetracker.unity3d.com/issues/...))`.
    - FogBugz is marked as "Resolved" with *next* release version correctly set.
- [ ] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [ ] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

2023-08-14 12:56 UTC, lyndon-unity requested changes
Some questions and suggestions above

2023-08-14 12:56 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/InputActionsEditorWindow.cs
> +            var clone = Instantiate(asset);
Does this just create a local copy of the asset rather than cloning it in the database?
If it clones it in the database it would be problematic.

2023-08-14 12:56 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/InputActionsEditorWindow.cs
> +            var clone = Instantiate(asset);
Do we at least need to delete this after making the serialized asset?

2023-08-14 12:56 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/InputActionsEditorWindow.cs
>                      var serializedAsset = new SerializedObject(asset);
Doesn't this flow also need to create the clone/copy?
Would be worth extracting this code out into a supporting function to remove dupliation

2023-08-14 12:56 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/InputActionsEditorWindow.cs
> +            titleContent = m_IsDirty ? new GUIContent("(*) Input Actions Editor") : new GUIContent("Input Actions Editor");
Suggest we only change the title if the dirty state has changed to avoid the GUIContent calls when no differences to dirty state.

2023-08-14 12:56 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/InputActionsEditorWindow.cs
> +            window.BuildUI();
Have you tested this flow. Does it work?
I ask as I'm wondering if you need to call SetAsset too ?

2023-08-16 13:56 UTC, ritamerkl commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/InputActionsEditorWindow.cs
> +            var clone = Instantiate(asset);
resolved as I found a better solution: 
now the old asset is restored from json after discarding changes- this is the cleanest solution without allocating the database

2023-08-17 12:36 UTC, lyndon-unity approved these changes
Saving and auto saving seems to work as expected for me.
This update looks good

2023-08-17 12:38 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/InputActionsEditorWindow.cs
> +            window.BuildUI();
Seems to work for me.

2023-08-17 12:48 UTC, ritamerkl commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/InputActionsEditorWindow.cs
> +            window.BuildUI();
It works now, (latest commit) - no need to SetAsset() as long as the properties get transferred

2023-08-17 13:18 UTC, merged