check through Profiler.BeginSample markers for early returns (uum-49019)
Unity-Technologies/InputSystem pull request #1774
Opened 2023-10-13 15:01 UTC by peterhall-unity3d

### Description

While looking into https://jira.unity3d.com/browse/UUM-49019 ("The Profiler shows incorrect data and spams the console with "Missing Profiler.EndSample" errors when there is an Input System Component in Scene and switching to profiling in Deep Mode") I noticed several other BeginSample calls that might be missing EndSample calls.

### Changes made

Ran through all the BeginSample calls looking for returns without a matching EndSample and fixed them up.

### Checklist

Before review:

- [X] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - FogBugz ticket attached, example `([case %number%](https://issuetracker.unity3d.com/issues/...))`.
    - FogBugz is marked as "Resolved" with *next* release version correctly set.
- [N/A] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [N/A] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

2023-10-16 13:06 UTC, ekcoh approved these changes
Thanks for addressing this @peterhall-unity3d. LGTM.

2023-10-16 13:59 UTC, Pauliusd01 commented
I am downloading/installing a couple of Editor branches to double check them as well. Will add my review at tomorrow morning at the latest in case they don't finish today

2023-10-16 14:20 UTC, Pauliusd01 commented
Profiler set to Edit Mode, without Deep profile, Scene needs to be running, get these errors on 2021.3.31f1:
```
Non-matching Profiler.EndSample (Every EndSample call must have a preceding BeginSample call within the same frame):
Previous 5 samples:
	GC.Alloc
	InputSystem.TryFindMatchingControlLayout
	GC.Alloc
	InputSystem.TryFindMatchingControlLayout
	Mono.JIT
In the scope:
	EditorApplication.playModeStateChanged: UnityEngine.InputSystem.LowLevel.NativeInputRuntime.OnPlayModeStateChanged
	UnityEditor.CoreModule.dll!UnityEditor::EditorApplication.Internal_PlayModeStateChanged() [Invoke]
	Application.Tick
	EditorLoop
	Main Thread
```
Does this qualify as a different bug? Or you'd say It's still the same one?  (Trunk works correct with both by the way Edit and Play mode profiling. So It's just the older Editor branches affected)

2023-10-17 07:42 UTC, Pauliusd01 requested changes
Updating status. Let me know if the issue above does not need to be solved in this same PR

2023-10-18 14:11 UTC, Pauliusd01 reviewed
Still having the error with these changes:

>D:\Git repo packages\InputSystem\Packages\com.unity.inputsystem\InputSystem\InputManager.cs(856,32): error CS1061: 'string' does not contain a definition for 'IsEmpty' and no accessible extension method 'IsEmpty' accepting a first argument of type 'string' could be found (are you missing a using directive or an assembly reference?)

AND

>D:\Git repo packages\InputSystem\Packages\com.unity.inputsystem\InputSystem\InputManager.cs(917,20): error CS0029: Cannot implicitly convert type 'string' to 'UnityEngine.InputSystem.Utilities.InternedString'

2023-10-20 08:38 UTC, Pauliusd01 approved these changes
Looks good now, I checked this in Edit/Play mode profiling in trunk, 2023.1 and 2021.3 switching between deep profile back and forth. Did not get any errors anymore on any of the branches

2023-10-23 09:22 UTC, merged