DOCS: DOCF-3771 updates to settings page
Unity-Technologies/InputSystem pull request #1810
Opened 2024-01-03 12:50 UTC by duckets

### Description

Updates to the settings documentation page.
https://jira.unity3d.com/browse/DOCF-3771

### Changes made

Some screenshots updated, some unnecessary screenshots removed. 
Minor text improvements.

2024-01-05 10:11 UTC, lyndon-unity requested changes
Bookmark tag needs fixing but otherwise changes look good

2024-01-05 10:11 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/Documentation~/Settings.md
> -![Play Mode Input Behavior](Images/PlayModeInputBehavior.png)
You removed a bookmark here that is referenced in other parts of the doc.

2024-01-05 16:40 UTC, lyndon-unity approved these changes

2024-01-08 13:20 UTC, ekcoh approved these changes
Thanks for this update Ben. LGTM!

2024-01-12 07:42 UTC, merged