FIX: composite part name editing (ISX-1734)
Unity-Technologies/InputSystem pull request #1814
Opened 2024-01-10 13:24 UTC by ritamerkl

### Description

This PR addresses the issue that composite parts where not editable and operate the dropdown menu changed the binding path instead. The ticket can be found [here](https://jira.unity3d.com/browse/ISX-1734). 

### Changes made

Fixed:
- editing composite parts
The problem was that the invoked command changed the m_Path of the binding and not like it shout the m_Name property.

### Checklist

Before review:

- [x] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - FogBugz ticket attached, example `([case %number%](https://issuetracker.unity3d.com/issues/...))`.
    - FogBugz is marked as "Resolved" with *next* release version correctly set.
- [ ] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [ ] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

2024-01-10 14:07 UTC, Pauliusd01 approved these changes
LGTM. Checked that the Composite Part option no longer messes with the path on different composite types. (Some, I was unable to check due to implementation issues like ISX-1817, but ones that are available work correctly now)

2024-01-10 14:59 UTC, ekcoh requested changes

2024-01-10 14:59 UTC, ekcoh commented on Packages/com.unity.inputsystem/CHANGELOG.md
> +- Fixed composite parts not editable issue
Could you rewrite this changelog item to provide more clarity on what previous symptom it resolves, it is quite unclear what it addresses in its current form. Also missing full-stop in the end.

2024-01-10 14:59 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Editor/Internal/InputActionSerializationHelpers.cs
> +            //expects nicified part name
Typo in comment

2024-01-12 08:43 UTC, ekcoh approved these changes
LGTM

2024-01-12 09:40 UTC, merged