FIX: Corrected behaviour of TrackedPoseDriver when no device is connected.
Unity-Technologies/InputSystem pull request #1823
Opened 2024-01-29 19:57 UTC by ekcoh

### Description

This fix is intended to fix reported behaviour in [ISXB-699
](https://issuetracker.unity3d.com/product/unity/issues/guid/ISXB-699).

### Changes made

Modified behaviour when action reference is not set or when binding count is zero to not track position nor rotation.

Added a test case that is mimicking the reported behavior.

### Notes

Requesting insights from XR team regarding any implications this might have since behavior wasn't previously covered properly in existing test cases. It also changes the behaviour commented inline in the implementation.

### Checklist

Before review:

- [ ] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - FogBugz ticket attached, example `([case %number%](https://issuetracker.unity3d.com/issues/...))`.
    - FogBugz is marked as "Resolved" with *next* release version correctly set.
- [ ] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [ ] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

2024-11-11 08:29 UTC, Pauliusd01 commented
@smnwttbr I don't have any XR devices so I'll add an XR QA instead. @UnityRyanC

2024-11-12 16:38 UTC, UnityRyanC commented
I won't be able to test this PR as I don't have a Mac (which the bug mentions was where the issue was reproduced on). I spoke with Manuel Gonzalez Solano, who does testing on PolySpatial and Apple Vision OS, who'll be able to test this once he's free later this week.

I don't have permission to update reviewers on this PR, so @Pauliusd01 could you update the PR for me please?

2024-11-13 07:24 UTC, Pauliusd01 commented
> I won't be able to test this PR as I don't have a Mac (which the bug mentions was where the issue was reproduced on). I spoke with Manuel Gonzalez Solano, who does testing on PolySpatial and Apple Vision OS, who'll be able to test this once he's free later this week.
> 
> I don't have permission to update reviewers on this PR, so @Pauliusd01 could you update the PR for me please?

Okay, I dmed him on slack since I can't find him on github by name.

2024-11-13 16:17 UTC, mangosol commented
@Pauliusd01 can you add me as reviewer? I don't seem to have permission to add myself

2024-11-22 18:24 UTC, mangosol reviewed
I tested the `isxb-699-trackedposedriver-fix` branch against a new Universal 3D project created and run using Unity Editor 6000.0.26f1 apple silicon on an M1 macOS machine.

I did observe that the non-origin position and rotation was preserved on GameObjects having `Tracked Pose Driver` components if I left the `Ignore Tracking State` checkbox enabled.

If I check the `Ignore Tracking State` checkbox, GameObjects having `Tracked Pose Driver` component and set at non-origin position and rotation are once again returned to origin position and rotation when PlayMode starts

I also observed that setting `Update Type = Before Render` with `Ignore Tracking State` checked, non-origin rotations and positions are preserved when starting PlayMode

2024-11-22 18:24 UTC, mangosol commented on Packages/com.unity.inputsystem/CHANGELOG.md
> +
nit: extra new line

2024-12-04 23:08 UTC, mangosol commented
I've also bound input actions to change position and rotation on GameObjects having TrackedPosedDriver component, and I observe the following: 

* When TrackedPoseDriver is configured with `Ignore Tracking State` unchecked, I am able to modify position and rotation, and the updated values persist.
* When TrackedPoseDriver is configured with `Ignore Tracking State` checked, and `Updated Type` is set `Update and Before Render` || `Update`, and `Tracking Type` is set to `Rotation and Position`, then any changes made to position and rotation are reset immediately after applied (likely on next frame).
* When TrackedPoseDriver is configured with `Ignore Tracking State` checked, and `Updated Type` is set `Update and Before Render` || `Update`, and `Tracking Type` is set to `Rotation only`, then any changes made to rotation are reset immediately after applied (likely on next frame). Position changes are applied successfully and persist.
* When TrackedPoseDriver is configured with `Ignore Tracking State` checked, and `Updated Type` is set `Update and Before Render` || `Update`, and `Tracking Type` is set to `Position only`, then any changes made to position are reset immediately after applied (likely on next frame). Rotation changes are applied successfully and persist.

2025-02-17 19:36 UTC, ekcoh commented on Packages/com.unity.inputsystem/CHANGELOG.md
> +
This was addressed in https://github.com/Unity-Technologies/InputSystem/pull/1823/commits/70d7db968de39490f5a6216a23ec8893ec5341b7

2025-02-17 19:39 UTC, ekcoh commented
> I've also bound input actions to change position and rotation on GameObjects having TrackedPosedDriver component, and I observe the following:
> 
> * When TrackedPoseDriver is configured with `Ignore Tracking State` unchecked, I am able to modify position and rotation, and the updated values persist.
> * When TrackedPoseDriver is configured with `Ignore Tracking State` checked, and `Updated Type` is set `Update and Before Render` || `Update`, and `Tracking Type` is set to `Rotation and Position`, then any changes made to position and rotation are reset immediately after applied (likely on next frame).
> * When TrackedPoseDriver is configured with `Ignore Tracking State` checked, and `Updated Type` is set `Update and Before Render` || `Update`, and `Tracking Type` is set to `Rotation only`, then any changes made to rotation are reset immediately after applied (likely on next frame). Position changes are applied successfully and persist.
> * When TrackedPoseDriver is configured with `Ignore Tracking State` checked, and `Updated Type` is set `Update and Before Render` || `Update`, and `Tracking Type` is set to `Position only`, then any changes made to position are reset immediately after applied (likely on next frame). Rotation changes are applied successfully and persist.

Thanks for the feedback @mangosol , I have taken this old PR back again since @smnwttbr worked on it to conclude this. How should I interpret your assessment, is it in line with what you would expect? Any additional feedback/perspective from @chris-massie?

2025-02-17 19:39 UTC, ekcoh commented
> I tested the `isxb-699-trackedposedriver-fix` branch against a new Universal 3D project created and run using Unity Editor 6000.0.26f1 apple silicon and 2022.3.51f1 apple silicon, on an M1 macOS machine.
> 
> I did observe that the non-origin position and rotation was preserved on GameObjects having `Tracked Pose Driver` components if I left the `Ignore Tracking State` checkbox enabled.
> 
> If I check the `Ignore Tracking State` checkbox, GameObjects having `Tracked Pose Driver` component and set at non-origin position and rotation are once again returned to origin position and rotation when PlayMode starts
> 
> I also observed that setting `Update Type = Before Render` with `Ignore Tracking State` checked, non-origin rotations and positions are preserved when starting PlayMode

Thanks for the feedback @mangosol , I have taken this old PR back again since @smnwttbr worked on it to conclude this. How should I interpret your assessment, is it in line with what you would expect? Any additional feedback/perspective from @chris-massie?

2025-02-18 15:27 UTC, mangosol commented
> Thanks for the feedback @mangosol , I have taken this old PR back again since @smnwttbr worked on it to conclude this. How should I interpret your assessment, is it in line with what you would expect? Any additional feedback/perspective from @chris-massie?

I do not have sufficient context on whether the behavior I observed is expected or not; my assessment is meant to describe current behavior for either you or any other stakeholder with more in depth knowledge of functional requirements to determine if the current behavior is expected or not given the changes in this PR. I'm happy to sign off if behavior is in line with requirements

2025-02-20 14:13 UTC, ekcoh commented
> > Thanks for the feedback @mangosol , I have taken this old PR back again since @smnwttbr worked on it to conclude this. How should I interpret your assessment, is it in line with what you would expect? Any additional feedback/perspective from @chris-massie?
> 
> I do not have sufficient context on whether the behavior I observed is expected or not; my assessment is meant to describe current behavior for either you or any other stakeholder with more in depth knowledge of functional requirements to determine if the current behavior is expected or not given the changes in this PR. I'm happy to sign off if behavior is in line with requirements

OK, thanks, I will do a review of this then and assess it and then make a decision based on that. Thanks for testing this through and carefully documenting observations. Its helpful.

2025-02-20 14:34 UTC, ekcoh commented on Packages/com.unity.inputsystem/CHANGELOG.md
> +
Will mark this resolved, feel free to reopen if you do not agree

2025-02-21 14:44 UTC, ekcoh commented
This PR have been updated based on reviewing implementation and previous suggested fix. I have updated the PR description accordingly. It would be fantastic if it would be possible to reassess this fix and ensure there are no regressive behavior in XR domain. @mangosol @chris-massie

2025-02-24 11:29 UTC, ritamerkl reviewed
Changes look good. I suggest outsourcing the HasResolvedControl method since it could be useful in more cases.

2025-02-24 11:29 UTC, ritamerkl commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +        private static bool HasResolvedControl(InputAction action)
This can be used and is a handy check in a broader sense than just for XR devices. Should we consider outsourcing it to a utils class?

2025-02-24 11:29 UTC, ritamerkl commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +                    m_CurrentPosition = transform.localPosition;
why using localPosition and not position here?

2025-02-24 11:29 UTC, ritamerkl commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +                if (HasResolvedControl(trackingStateAction))
the check is redundant with the else if statement above - HasResolvedControl(trackingStateAction))

2025-02-25 13:20 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +        private static bool HasResolvedControl(InputAction action)
The reason I didn't want to move it out is that its a far from ideal check (does a lot of work) and this is the only place its being used. I think I prefer keeping it here unless a specific use case for it has surfaced.

2025-02-25 13:20 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +                    m_CurrentPosition = transform.localPosition;
Since the component seem to be used to operate on the local position rather than the global position. I.e. the setter applies local position.

2025-02-25 13:23 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +                if (HasResolvedControl(trackingStateAction))
Thanks, good catch, I must have messed up when changing this function too many times. Will address this and comment in this thread once fixed.

2025-02-25 13:57 UTC, ritamerkl commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +                    m_CurrentPosition = transform.localPosition;
Okay, in that case I think it is fine

2025-02-25 13:57 UTC, ritamerkl commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +        private static bool HasResolvedControl(InputAction action)
Makes sense, let's consider moving it then if/when another use case pops up.

2025-02-25 13:59 UTC, ritamerkl approved these changes

2025-02-25 16:11 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +                if (HasResolvedControl(trackingStateAction))
This has been addressed in https://github.com/Unity-Technologies/InputSystem/pull/1823/commits/7260a9bc97cf20699be72f5a520c3f6d911ae648

2025-02-26 00:31 UTC, vrdave-unity requested changes
A couple of minor tweaks.

2025-02-26 00:31 UTC, vrdave-unity commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +                        return true;
While the [Unity-Meta project style guideline](https://github.cds.internal.unity3d.com/unity/unity-meta/blob/stable/ReferenceSource/CSharp/Assets/CSharpReference.cs#L231) doesn't explicitly call it out, putting spaces between un-braced conditional logic makes it more readable and less prone to accidental coding mistakes in the future.

```suggestion
                    if (bindingState.actionIndex != actionIndex)
                        continue;

                    if (bindingState.isComposite)
                        continue;

                    if (bindingState.controlCount > 0)
                        return true;
```

2025-02-26 00:31 UTC, vrdave-unity commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +                var hasRotationInputActionWithBindings = HasResolvedControl(rotationInput.action);
For consistency, should we use the private field here as we did above?

Also, we could save on these 'expensive' `HasResolvedControl` calls by using the previous calculation in the `UpdateCallback` method and passing it into the `ReadTrackingState` as parameters.

```suggestion
                var hasPositionInputActionWithBindings = HasResolvedControl(m_PositionInput.action);
                var hasRotationInputActionWithBindings = HasResolvedControl(m_RotationInput.action);
```

2025-02-27 11:28 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +                        return true;
I am not going to argue against that so will update accordingly. :) Will post with commit ID here once done.

2025-02-27 12:01 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +                var hasRotationInputActionWithBindings = HasResolvedControl(rotationInput.action);
Sure, no strong opinion, will update and post commit ID once done.

2025-02-27 12:07 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +                var hasRotationInputActionWithBindings = HasResolvedControl(rotationInput.action);
Suggestion to avoid calculation is great, overlooked it since it was split into two functions

2025-02-27 12:11 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +                var hasRotationInputActionWithBindings = HasResolvedControl(rotationInput.action);
Addressed in https://github.com/Unity-Technologies/InputSystem/pull/1823/commits/6b5c6a2af9288169032ebf9b3364e8fd2de18ae7, feel free to resolve if sufficient.

2025-02-27 12:11 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +                        return true;
Addressed in https://github.com/Unity-Technologies/InputSystem/pull/1823/commits/6b5c6a2af9288169032ebf9b3364e8fd2de18ae7, feel free to resolve if sufficient.

2025-02-27 12:12 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +                        return true;
Realise now you did it as a suggestion, but commit should be equivalent.

2025-02-27 12:12 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Plugins/XR/TrackedPoseDriver.cs
> +                if (HasResolvedControl(trackingStateAction))
Marking resolved for now.

2025-02-27 12:14 UTC, ekcoh commented on Packages/com.unity.inputsystem/CHANGELOG.md
> +
Marking this resolved now

2025-02-27 17:23 UTC, vrdave-unity approved these changes
These changes look good. I don't think it should impact performance too much since the HasResolvedControl calls only happen during the first update.

2025-02-27 19:02 UTC, chris-massie requested changes

2025-02-27 19:02 UTC, chris-massie commented on Assets/Tests/InputSystem/Plugins/XRTests.cs
> +    [Category("Components")]
```suggestion
    [Test]
    [Category("Components")]
```
This test won't actually execute without `[Test]`.

2025-02-27 19:07 UTC, chris-massie commented on Assets/Tests/InputSystem/Plugins/XRTests.cs
> +        // i.e. that rotation and/or position is not updated if device is not connected and track state isn't ignored.
```suggestion
    [TestCase(false)]
    [TestCase(true)]
    public void Components_TrackedPoseDriver_RetainsPoseWhenNoActionIsBound(bool ignoreTrackingState)
    {
        // Tests/reproduces the scenario described in https://issuetracker.unity3d.com/product/unity/issues/guid/ISXB-699
        // i.e. that rotation and/or position is not updated if device is not connected.
```
This is actually the case whether `ignoreTrackingState` is `false` or `true`. This suggestion adds two `TestCase`. Combine this suggestion with the other one that uses the test parameter.

2025-02-27 19:07 UTC, chris-massie commented on Assets/Tests/InputSystem/Plugins/XRTests.cs
> +        tpd.ignoreTrackingState = false;
```suggestion
        tpd.ignoreTrackingState = ignoreTrackingState;
```

2025-02-28 08:37 UTC, ekcoh commented
@chris-massie I have applied all your suggestions to the PR and re-run CI on the branch. Hence requesting re-review. Additionally do you think an additional QA pass is needed from @mangosol or other XR QA before this lands or not?

2025-02-28 18:16 UTC, chris-massie approved these changes
I tested these changes out with the XRI simulator and it seemed to work as I expected where the existing pose is retained if there's no device. If I connect the device late the Transform stays at the initialized pose until a change from (0, 0, 0) happens on the device, at which point it updates as expected.

2025-02-28 20:03 UTC, ekcoh commented
Thanks @chris-massie and @vrdave-unity for the latest reviews and testing, it was very valuable. I will get this merged based on this.

2025-03-03 10:01 UTC, merged