ISXB-389 and ISXB-371 -  Action Execution Order Docs
Unity-Technologies/InputSystem pull request #1826
Opened 2024-01-31 14:49 UTC by duckets

### Description

Clarifying that action event execution order is undefined.
https://jira.unity3d.com/browse/ISXB-389
https://jira.unity3d.com/browse/ISXB-371
https://jira.unity3d.com/browse/DOCF-3908

### Changes made

Added notes to multiple pages warning users that event execution order is undefined and not to write code based on assuming the order is as appears in the UI.

2024-01-31 15:57 UTC, lyndon-unity requested changes
Text looks ok but one of the links is reporting an error

2024-01-31 15:57 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/Documentation~/Actions.md
> +> - Actions are a runtime only feature. You can't use them in [Editor window code](xref:EditorWindow).
An error is reported in the test run about this line
https://unity-ci.cds.internal.unity3d.com/job/33610680/results

Message: Expected: <empty> But was: < "xref:EditorWindow in C:\build\output\Unity-Technologies\InputSystem\Temp\docstest\com.unity.inputsystem@1.8\manual\Actions.html (File Not Found)" > StackTrace: at DocumentationBasedAPIVerficationTests.API_DocumentationManualDoesNotHaveMissingInternalLinks () [0x0004a] in C:\build\output\Unity-Technologies\InputSystem\Assets\Tests\InputSystem\DocumentationBasedAPIVerficationTests.cs:90 Test

2024-02-01 13:33 UTC, ekcoh approved these changes
Nothing to add outside feedback already added by @lyndon-unity . Good you clarified what to expect and not to expect from action ordering, especially since the same is not true for other ordering in the same window, e.g. processors and interactions.

2024-02-27 13:16 UTC, lyndon-unity approved these changes

2024-03-01 07:56 UTC, merged