Add UI Toolkit matching control bindings UX
Unity-Technologies/InputSystem pull request #1835
Opened 2024-02-08 10:56 UTC by lyndon-unity

### Description

Implemented UI TK version of the matching control bindings recently added to the UGUI editor
https://github.com/Unity-Technologies/InputSystem/pull/1672

Example of it working in the project wide input actions. This is the same UX used in the individual assets.
![image](https://github.com/Unity-Technologies/InputSystem/assets/33493311/2f4ec3f2-247d-4d39-966e-e04a8cec55d5)

### Changes made

The code to populate the UX is the same as the UGUI code - but split out to generate a tree before then generating the UI specific tree.

Also fixed up some styling on the control scheme info which is in the binding UI to be more consistent with the UGUI version. Bolded and fixed margins.

### Checklist

Before review:

- Changelog entry added.
- No tests added/changed
- No new doc

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

2024-02-08 13:37 UTC, ritamerkl reviewed
Good to see this working! 
I just have one major point- I think it could be worth outsourcing the biggest part of the DrawMatchingControlPath and connected methods to an external script (or other related existing classes). Like that we could keep the PropertiesView clean and "logic free". 
I also added one minor comment on a potential unused method to remove.

2024-02-08 13:37 UTC, ritamerkl commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/Views/BindingPropertiesView.cs
> +        }
Is this method unused?

2024-02-08 14:30 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/Views/BindingPropertiesView.cs
> +        }
Yes I think I forgot to remove - will do that now.

2024-02-08 14:31 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/UITKAssetEditor/Views/BindingPropertiesView.cs
> +        }
Removed now.

2024-02-08 14:32 UTC, lyndon-unity commented
> Good to see this working! I just have one major point- I think it could be worth outsourcing the biggest part of the DrawMatchingControlPath and connected methods to an external script (or other related existing classes). Like that we could keep the PropertiesView clean and "logic free". I also added one minor comment on a potential unused method to remove.

Yes I agree I can take a look at spitting those out

2024-02-08 15:00 UTC, ritamerkl approved these changes
LGTM now

2024-02-09 11:37 UTC, Pauliusd01 commented
Is the style used wrong? Why is the derived binding text selectable? It wasn't like that in the IMGUI version and I don't see why that should be changed

2024-02-09 11:48 UTC, Pauliusd01 commented
https://github.com/Unity-Technologies/InputSystem/assets/54306142/d77c6a20-4fc2-43e3-b976-4d44f3b3cc78

Since this is a toggle now I think its state should be saved, seems annoying to have to re-enable it between window restarts

2024-02-09 11:49 UTC, Pauliusd01 requested changes
Just minor notes from me. Functionality seems the same and works without issues

2024-02-09 17:49 UTC, lyndon-unity commented
> Is the style used wrong? Why is the derived binding text selectable? It wasn't like that in the IMGUI version and I don't see why that should be changed

I've fixed that - it was just the default for the UI TK tree view.
I've set it to none to match IMGUI version

2024-02-09 17:49 UTC, lyndon-unity commented
> I think its state should be saved

I'd like to do that but I don't have a quick fix for that so might land the update so far and look at that later.

2024-02-12 12:21 UTC, Pauliusd01 commented
> > I think its state should be saved
> 
> I'd like to do that but I don't have a quick fix for that so might land the update so far and look at that later.

Does it have to be a toggle then? If a foldout would solve this issue I'd prefer that, and later on we can switch it to a toggle once state saving is there

2024-02-12 15:32 UTC, lyndon-unity commented
> > > I think its state should be saved
> > 
> > 
> > I'd like to do that but I don't have a quick fix for that so might land the update so far and look at that later.
> 
> Does it have to be a toggle then? If a foldout would solve this issue I'd prefer that, and later on we can switch it to a toggle once state saving is there

State is now maintained over open/close to match IMGUI.
I've just switched to a foldout now too.

2024-02-12 18:45 UTC, ekcoh approved these changes
LGTM, is all logic in MatchingControlPaths new? If it is then its fine as-is, otherwise it might be worthwhile avoiding duplicating logic with existing feature implementation for IMGUI? It seems like MatchingControlPaths is not tied to UI framework and would be possible to cover with unit tests?

2024-02-12 21:11 UTC, lyndon-unity commented
> LGTM, is all logic in MatchingControlPaths new? If it is then its fine as-is, otherwise it might be worthwhile avoiding duplicating logic with existing feature implementation for IMGUI? It seems like MatchingControlPaths is not tied to UI framework and would be possible to cover with unit tests?

The MatchingControlPaths isn't all new code - its adapted from the IMGUI version. It drops some of the code for retaining the expand/collapse state of individual parts of the hierarchy as that had a static dictionary that seemed lower priority for the memory overheads. To use in IMGUI directly we would have to add back in the static dictionary and store extra state in the returned data. I decided to duplicate as the IMGUI version would be deprecated in future.

Tests should be added but I felt given time constraints that part could be added later.

2024-02-13 06:34 UTC, Pauliusd01 approved these changes
LGTM, checked that the matching bindings are correct for different bindings in both ProjectWideActions and custom action assets.

2024-02-13 08:38 UTC, ekcoh commented
> > LGTM, is all logic in MatchingControlPaths new? If it is then its fine as-is, otherwise it might be worthwhile avoiding duplicating logic with existing feature implementation for IMGUI? It seems like MatchingControlPaths is not tied to UI framework and would be possible to cover with unit tests?
> 
> The MatchingControlPaths isn't all new code - its adapted from the IMGUI version. It drops some of the code for retaining the expand/collapse state of individual parts of the hierarchy as that had a static dictionary that seemed lower priority for the memory overheads. To use in IMGUI directly we would have to add back in the static dictionary and store extra state in the returned data. I decided to duplicate as the IMGUI version would be deprecated in future. ^ but I have now removed duplicated code and refactored a little so it can be shared with IMGUI and UI TK.
> 
> Tests should be added but I felt given time constraints that part could be added later.

I see, great to avoid duplicating too much. OK to postpone the test part temporarily but in that case please file a ticket on the remaining part from your perspective.

2024-02-14 08:31 UTC, merged