NEW: Device filtering support (ISX-1481)
Unity-Technologies/InputSystem pull request #1840
Opened 2024-02-14 11:03 UTC by ritamerkl

### Description

This PR adds device filtering support for control schemes that was already implemented in the IMGUI input action asset editor. The related ticket can be found [here](https://jira.unity3d.com/browse/ISX-1481).

### Changes made

added:
- enable/disable toolbar menu if device filtering is available/unavailable
- showing the correct menu items and marking current selection
- filtering bindings for matching devices

### Checklist

Before review:

- [x] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - FogBugz ticket attached, example `([case %number%](https://issuetracker.unity3d.com/issues/...))`.
    - FogBugz is marked as "Resolved" with *next* release version correctly set.
- [ ] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [ ] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

2024-02-15 20:57 UTC, ekcoh approved these changes
It was a bit difficult to fully understand all logic in this PR. Have the functionality been tested in combination with copy/paste and drag/drop? Otherwise I would suggest doing that in QA phase to make sure that when items are filtered out any index accessing is still operating correctly.

2024-02-16 12:12 UTC, ritamerkl commented
> It was a bit difficult to fully understand all logic in this PR. Have the functionality been tested in combination with copy/paste and drag/drop? Otherwise I would suggest doing that in QA phase to make sure that when items are filtered out any index accessing is still operating correctly.

I tested it roughly, I agree that it's worth waiting for a QA test.

2024-02-18 09:19 UTC, lyndon-unity approved these changes
Functionally seems consistent with IMGUI version and a good step up where the feature was previously missing

2024-02-19 12:43 UTC, Pauliusd01 requested changes
Actual filtering does not seem to work, if I select one of the devices my binding list is unfilitered. Here's a video of current UITK version and the IMGUI one below
https://github.com/Unity-Technologies/InputSystem/assets/54306142/44f8a680-67bf-40ec-9547-9f1e8f7b8d13


https://github.com/Unity-Technologies/InputSystem/assets/54306142/8deada1f-d865-458f-8f3b-96989d8402f4

2024-02-19 12:58 UTC, ritamerkl commented
> Actual filtering does not seem to work, if I select one of the devices my binding list is unfilitered. Here's a video of current UITK version and the IMGUI one below https://github.com/Unity-Technologies/InputSystem/assets/54306142/44f8a680-67bf-40ec-9547-9f1e8f7b8d13
> 
>  Unity_2024-02-19_14-42-39.mp4

should be fixed now, there was a problem with filtering "global" bindings (bindings not assigned to any control schemes). @Pauliusd01

2024-02-19 13:49 UTC, Pauliusd01 commented
Devices list does not update if the scheme is changed. For example if you have keyboard in your scheme -> you remove it -> the device list still shows keyboard in its list and throws this error when selected:

```
Specified argument was out of the range of valid values.
Parameter name: index
UnityEditor.RetainedMode:UpdateSchedulers () (at D:/Gitrepo/unity/Modules/UIElementsEditor/RetainedMode.cs:57)

```

2024-02-20 09:43 UTC, Pauliusd01 approved these changes
LGTM. Checked that the binding list is correctly filtered between will all types of devices, in different scheme context (whether they are assigned to a scheme or global), filtering persists when selecting different maps and made sure there's no other functionality differences between the IMGUI version.

2024-02-20 12:05 UTC, merged