added more information in the dialog to restart the editor.
Unity-Technologies/InputSystem pull request #1913
Opened 2024-04-24 03:43 UTC by smnwttbr

### Description

When the editor is restarted, pending import operations and windows are closed. The dialog has added information to inform the  user of this.

### Changes made

Modified dialog text.

![image](https://github.com/Unity-Technologies/InputSystem/assets/26544356/c7b99417-059a-427b-b77a-1c2246952307)

### Checklist

Before review:

- [ ] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - FogBugz ticket attached, example `([case %number%](https://issuetracker.unity3d.com/issues/...))`.
    - FogBugz is marked as "Resolved" with *next* release version correctly set.
- [ ] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [ ] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

2024-04-24 03:43 UTC, unity-cla-assistant commented
[![CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/pull/badge/not_signed)](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/InputSystem?pullRequest=1913) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/InputSystem?pullRequest=1913) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/InputSystem?pullRequest=1913) it.</sub>

2024-04-24 06:29 UTC, ekcoh requested changes
This small clarification looks good to me. I would however add @duckets as a reviewer on this PR since he is the technical writer on the team and can support in following language and communication consitency guidelines for this kind of user feedback. Include @duckets as reviewer on anything involving dialogs, UI text, public API docs or manual updates.

I will request changes though since the CHANGELOG.md file needs to be updated with a notice under the Changed header about this modification (even if non-functional it makes sense to include it and to get into process with this PR).

2024-04-24 06:30 UTC, ekcoh commented
In addition the PR is in draft status, you should convert it into a regular PR if there are no further changes planned on it. We typically use drafts only to get some feedback when work is pending / not finished.

2024-04-24 06:31 UTC, ekcoh commented
I also see you need to sign the license/CLA for CI to pass on this one. This is a one time thing you need to do to contribute to the repo.

2024-04-26 06:18 UTC, ekcoh approved these changes
LGTM

2024-04-30 13:54 UTC, duckets commented
Hi, two things:
1) I assume we've exhausted all other options that don't require this workaround, such as whether it's possible to delay showing this dialog until all importing is complete?
2) Doesn't restarting the editor automatically continue the import for anything that's not yet imported? When we say the user has to start (or restart) the import process after the editor restarts, where exactly is this button to do this?

2024-06-13 09:17 UTC, duckets commented
I'm reluctant to approve this because although technically it explains to the user what to do, even with the improved text, I still think it's a bad user experience and, it's something that first-time Unity users have a high chance of encountering when importing their first demo project or starting their own first project using asset store assets. Therefore it has the potential to be one of the very first things any user experiences when starting their first project in the editor, which I think should be given significantly elevated priority as a user experience.

If it's at all possible, I think it needs looking at more closely and maybe going back to engineers for a solution that doesn't interrupt the package dependency import process.

2024-06-13 09:22 UTC, duckets approved these changes
As noted in the discussion, approved because the text is now clearer, but overall I don't think it's acceptable to ask potentially brand-new users to restart the editor and then have to remember to restart the package import process. See full comment in PR conversation!

2025-10-21 09:56 UTC, ekcoh commented
Updated this branch with critical CI fix from develop.

2026-01-29 08:32 UTC, Pauliusd01 commented
Closing this as the dialog is planned to be reworked and the changes are expected to be quite different from what is proposed here

2026-01-29 08:32 UTC, closed without merging