CHANGE: Make DualSenseHIDInputReport public so it can be used in child devices
Unity-Technologies/InputSystem pull request #1945
Opened 2024-05-31 11:20 UTC by lewish-unity

### Description

Made the input report for the DualsenseHID gamepad public so that it can be used in child devices as input reports. 
This fixes [ISXB-652](https://issuetracker.unity3d.com/product/unity/issues/guid/ISXB-652) in combination with fixes in other packages.

### Changes made

- Made DualSenseHIDInputReport public
- Added tests for recognising the Dualsense Controller 

### Checklist

Before review:

- [x] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - FogBugz ticket attached, example `([case %number%](https://issuetracker.unity3d.com/issues/...))`.
    - FogBugz is marked as "Resolved" with *next* release version correctly set.
- [x] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [ ] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [x] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

2024-05-31 11:20 UTC, unity-cla-assistant commented
[![CLA assistant check](https://cla-assistant.cds.internal.unity3d.com/pull/badge/not_signed)](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/InputSystem?pullRequest=1945) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.cds.internal.unity3d.com/Unity-Technologies/InputSystem?pullRequest=1945) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.cds.internal.unity3d.com/check/Unity-Technologies/InputSystem?pullRequest=1945) it.</sub>

2024-06-11 07:08 UTC, ekcoh requested changes
Changes LGTM apart from CHANGELOG.md not being updated as part of this PR. Could you add a line under our unreleased version under CHANGED that DualSenseHIDInputReport was changed from internal to public visibility? 

(We should make sure to release a minor revision next time due to this change.)

2024-06-18 09:25 UTC, ekcoh approved these changes

2024-06-18 09:25 UTC, ekcoh commented on Packages/com.unity.inputsystem/CHANGELOG.md
> +- Changed DualSenseHIDInputReport from internal to public visibility
Minor, but when referencing type/code use `Code Formatting` since an .md file

2024-06-18 11:57 UTC, ritamerkl approved these changes

2024-06-18 12:28 UTC, Pauliusd01 commented
Don't see anything wrong with the changes but this does not fix [ISXB-652](https://issuetracker.unity3d.com/product/unity/issues/guid/ISXB-652), I still see the actual result from the bug description

![image](https://github.com/Unity-Technologies/InputSystem/assets/54306142/a4006b69-3cc0-4686-9349-51ea64c8789f)

2024-06-18 12:58 UTC, Pauliusd01 approved these changes

2024-06-21 16:09 UTC, timkeo approved these changes

2024-06-25 10:17 UTC, ekcoh commented
@lewish-unity I noticed there is a CI failure on this one https://unity-ci.cds.internal.unity3d.com/job/38452361?utm_source=github I believe you need to update version number in package.json from "1.8.3" to "1.9.0" for API change to not generate an error.

2024-06-25 10:34 UTC, lewish-unity commented
Will do, I thought this might happen with a different PR but will update it in my branch

2024-06-25 15:57 UTC, merged