FIX: ISXB-1153 fix exception on paste to empty actionmap list
Unity-Technologies/InputSystem pull request #2042
Opened 2024-10-31 04:57 UTC by smnwttbr

### Description

Fixed an exception when pasting an action map into an empty action map list.  [ISXB-1150](https://issuetracker.unity3d.com/product/unity/issues/guid/ISXB-1150)

### Testing status & QA

local package tests succeeded.

### Overall Product Risks

- Complexity:  low
- Halo Effect: small

### Comments to reviewers

_Please describe any additional information such as what to focus on, or historical info for the reviewers._

### Checklist

Before review:

- [ ] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - JIRA ticket linked, example ([case %<ID>%](https://issuetracker.unity3d.com/product/unity/issues/guid/<ID>)). If it is a private issue, just add the case ID without a link.
    - Jira port for the next release set as "Resolved".
- [ ] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [ ] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

After merge:

- [ ] Create forward/backward port if needed. If you are blocked from creating a forward port now please add a task to ISX-1444.

2024-10-31 08:01 UTC, Pauliusd01 commented
Getting an "Invalid action index to insert bindings before." error when pasting an action to an empty action list (does not occur on stable)

https://github.com/user-attachments/assets/5fb59a05-f8a2-49aa-a2c3-6e51a8c10d6a

2024-10-31 09:55 UTC, ritamerkl approved these changes

2024-10-31 10:07 UTC, Pauliusd01 requested changes
Just updating status

2024-11-06 09:18 UTC, Pauliusd01 approved these changes
LGTM, found 2 more paste related bugs but they're not regressions so will file those separately. Checked: cut/copy pasting maps, actions and bindings between assets when they're empty, have assets, when the thing I'm cutting is the last on the list, when the actions/maps aren't saved yet in either asset (all with shortcuts and context menu). Also, undo/redo workflow and auto save behaviour.

2024-11-12 04:19 UTC, merged