DOCS: Updated InputControl documentation
Unity-Technologies/InputSystem pull request #2078
Opened 2024-12-05 18:22 UTC by lyndon-unity

### Description

Updated InputControl documentation

### Testing status & QA

Reviewed generated docs using the DocTools package and checked the validation results

### Overall Product Risks

- Complexity: low
- Halo Effect: low

### Comments to reviewers

### Checklist

Before review:

- [ ] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - JIRA ticket linked, example ([case %<ID>%](https://issuetracker.unity3d.com/product/unity/issues/guid/<ID>)). If it is a private issue, just add the case ID without a link.
    - Jira port for the next release set as "Resolved".
- [ ] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [X] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

After merge:

- [ ] Create forward/backward port if needed. If you are blocked from creating a forward port now please add a task to ISX-1444.

2024-12-06 13:09 UTC, duckets requested changes

2024-12-06 13:09 UTC, duckets commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// List of aliased alternate names for the control. And example alias would be North for the Triangle button on a Playstation pad (or 'Y' button on Xbox pad).
```suggestion
        /// List of aliased alternate names for the control. An example of an alias would be North for the Triangle button on a Playstation pad (or 'Y' button on Xbox pad).
```

2024-12-06 13:09 UTC, duckets commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// A control layout will specific if it is synthetic using <see cref="InputControlLayout.ControlItem.isSynthetic"/>.
```suggestion
        /// A control layout will specify if it is synthetic using <see cref="InputControlLayout.ControlItem.isSynthetic"/>.
```

2024-12-06 13:09 UTC, duckets commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// <param name="bufferSize">Size of <paramref name="buffer"/> in bytes. which must be large enough to store the value.</param>
```suggestion
        /// <param name="bufferSize">Size of <paramref name="buffer"/> in bytes, which must be large enough to store the value.</param>
```

2024-12-06 13:09 UTC, duckets commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// The type of the state memory associated with the control
```suggestion
        /// The type of the state memory associated with the control.
```

2024-12-09 16:01 UTC, ekcoh requested changes
Lots of missing docs added, great you adressed this. Have a bunch of minor comments to address.

2024-12-09 16:01 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// control has no short name, its long name will be used instead. See <see cref="displayName"/>
Missing full stop

2024-12-09 16:01 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// will point to itself. (See <see cref="InputDevice.allControls"/>)
Missing full stop

2024-12-09 16:01 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// (which, once fully constructed, will only be the case for InputDevices). <see cref="children"/>
missing full stop at end?

2024-12-09 16:01 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// <see cref="parent"/>
This would result in "Does not allocate. parent"? Would recommend in incorporating reference in a sentence explaining why its relevant or exclude it?

2024-12-09 16:01 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// List of aliased alternate names for the control. And example alias would be North for the Triangle button on a Playstation pad (or 'Y' button on Xbox pad).
Since this is referencing strings, shouldn't North and Triangle be quoted and use <c> formatting?

2024-12-09 16:01 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// Information about where the control stores its state, such as format, offset and size.
Repeating text in summary and <value> which is not recommended. I would suggest replacing summary with the <value> text and remove <value> section?

2024-12-09 16:01 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// A control layout will specific if it is synthetic using <see cref="InputControlLayout.ControlItem.isSynthetic"/>.
Typo "will" instead of "with"?

2024-12-09 16:01 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// <value>
I believe <value> will generate negative score with our tool even if it's the standard C# way of documenting properties. Would recommend combining it with summary and remove section.

2024-12-09 16:01 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// Return a string representation of the control. Useful for debugging.
Do we need this or <inheritdoc/>, shouldn't be different than object.ToString right?

2024-12-09 16:01 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// <remarks>
Is the remarks really needed for ctor? Otherwise remove it since redundant.

2024-12-09 16:01 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// Refresh Configuration
Suggesting summary instead to be a readable sentence, e.g. "Refreshes the controls configuration when applicable."

2024-12-09 16:01 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// Calculates and returns an optimized data type that can represent a control's value in memory directly.
Maybe omit redundant info from remarks?

2024-12-09 17:29 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// List of aliased alternate names for the control. And example alias would be North for the Triangle button on a Playstation pad (or 'Y' button on Xbox pad).
Good spot. Done

2024-12-09 17:30 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// A control layout will specific if it is synthetic using <see cref="InputControlLayout.ControlItem.isSynthetic"/>.
Done in latest commit.

2024-12-09 17:30 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// <param name="bufferSize">Size of <paramref name="buffer"/> in bytes. which must be large enough to store the value.</param>
Done in latest commit. Thank you.

2024-12-09 17:30 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// The type of the state memory associated with the control
Done in latest commit. Thank you

2024-12-09 17:31 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// control has no short name, its long name will be used instead. See <see cref="displayName"/>
Thanks. You are so much better at spotting those. Done in latest commit.

2024-12-09 17:32 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// (which, once fully constructed, will only be the case for InputDevices). <see cref="children"/>
Done

2024-12-09 17:33 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// <see cref="parent"/>
Done

2024-12-09 17:33 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// will point to itself. (See <see cref="InputDevice.allControls"/>)
Added

2024-12-09 17:37 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// List of aliased alternate names for the control. And example alias would be North for the Triangle button on a Playstation pad (or 'Y' button on Xbox pad).
Done in latest commit

2024-12-09 17:38 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// <value>
Done in recent commit.

2024-12-09 17:40 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// Return a string representation of the control. Useful for debugging.
Not sure I understand this query. Agreed its no different. Are you suggesting use  inheritdoc ?
not sure that works if its not in the same file.

2024-12-09 17:41 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// <remarks>
Docs code said it was required. I agree its not great but I couldn't think of much more to say here.

2024-12-09 17:42 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// Refresh Configuration
Agreed, revised to 
>Refreshes the controls configuration.

2024-12-09 17:42 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// Calculates and returns an optimized data type that can represent a control's value in memory directly.
Agreed, done.

2024-12-09 17:54 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// Information about where the control stores its state, such as format, offset and size.
Done in next commit

2024-12-09 17:55 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// A control layout will specific if it is synthetic using <see cref="InputControlLayout.ControlItem.isSynthetic"/>.
Already updated with:
A control layout will specify if it is synthetic using ...

2024-12-10 12:04 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// Return a string representation of the control. Useful for debugging.
Yes that was what I suggested, sorry if it was unclear.

2024-12-10 12:05 UTC, ekcoh commented on Packages/com.unity.inputsystem/InputSystem/Controls/InputControl.cs
> +        /// <remarks>
OK, too bad the docs format require things like these when it doesn't make sense :/

2024-12-10 12:05 UTC, ekcoh approved these changes

2024-12-11 09:05 UTC, merged