FIX: Arrow key navigation of Input Actions after Action rename.
Unity-Technologies/InputSystem pull request #2082
Opened 2024-12-09 15:47 UTC by tspiller

### Description

ActionsTreeView should use RefreshItems in Unity 6000.0 onwards to have the same behaviour as ActionMapsView. This allows keyboard navigation after renaming.
It is not a perfect fix, as the limitations of UIToolkit and InputSystem refresh mean that the action will still lose focus occasionally. However this is the current behaviour of Action Maps and Actions should match that as closely as possible.

### Testing status & QA

Local Testing.
Added new CanRenameAction test.

### Overall Product Risks

Complexity: Low
Halo Effect: None

### Comments to reviewers

### Checklist

Before review:

- [X] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - JIRA ticket linked, example ([case %<ID>%](https://issuetracker.unity3d.com/product/unity/issues/guid/<ID>)). If it is a private issue, just add the case ID without a link.
    - Jira port for the next release set as "Resolved".
- [X] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [ ] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

After merge:

- [ ] Create forward/backward port if needed. If you are blocked from creating a forward port now please add a task to ISX-1444.

2024-12-09 16:04 UTC, ekcoh approved these changes
Changes LGTM, thanks for adding a corresponding test case to prevent future regression.

2024-12-09 16:04 UTC, ekcoh commented on Assets/Tests/InputSystem.Editor/InputActionsEditorTests.cs
> +    public IEnumerator CanRenameAction()
Awesome you've added a proper editor test for this. Thank you!

2024-12-10 10:29 UTC, Pauliusd01 requested changes
Context menu messes up if you right click in rename mode. (Double click on an action to enter rename mode -> rightclick)
https://github.com/user-attachments/assets/ca2a15c9-78ff-4aa0-81fe-b896ad821c5c

2024-12-10 10:30 UTC, Pauliusd01 commented
If you duplicate while in rename mode that action stays in rename mode instead of cancelling it
https://github.com/user-attachments/assets/3e5d0b43-35a9-4902-8cc5-bcecf3686a17

2024-12-10 10:32 UTC, Pauliusd01 commented
Odd behaviour after renaming a map -> action and then action again


https://github.com/user-attachments/assets/d61cebbb-9bed-4790-ae5d-a08b2150a2c1

2025-01-08 13:23 UTC, Pauliusd01 requested changes
Still seeing the context menu issues
https://github.com/user-attachments/assets/a96ee113-e232-4fac-aacd-af6fabf6f318

2025-01-16 13:50 UTC, tspiller commented
> Still seeing the context menu issues https://github.com/user-attachments/assets/a96ee113-e232-4fac-aacd-af6fabf6f318

@Pauliusd01 Turns out this wasn't happening on Mac, only on Windows which is why I thought I'd fixed it already. Should be fixed in https://github.com/Unity-Technologies/InputSystem/pull/2082/commits/f010303290986bf3062b25ec1ccc6f10f4c3488e

2025-01-20 11:44 UTC, Pauliusd01 requested changes
Context menu issues still present, slightly different repro though: Create a new action -> create a new binding for it -> right-click on that newly created binding


https://github.com/user-attachments/assets/e2e76ed4-60eb-4859-a9bb-a7c19cf792c2

2025-02-05 10:57 UTC, Pauliusd01 requested changes
Context menu for highlighted text has more options that it should/had before. And using the delete option throws a nullexception
https://github.com/user-attachments/assets/ec843368-fac3-42c1-b4cc-485bcc2a465a

2025-02-06 07:48 UTC, Pauliusd01 approved these changes

2025-02-10 12:29 UTC, merged