NEW: Throw error when extension for inputsystem needed
Unity-Technologies/InputSystem pull request #2101
Opened 2024-12-30 12:32 UTC by ritamerkl

### Description

Trying to use Input System package on console without the NDA package installed outputs an error message to the user.
The error is thrown in [OnInitializeLoad] and performs on loading a project, on switching platforms and domain reload.

### Testing status & QA

Manual testing for Switch platform.
Platforms missing: (which should surface this error without the installed Plugin)
-gamecore
-playstation (4&5)
-switch
-xboxone

### Overall Product Risks

_Please rate the potential complexity and halo effect from low to high for the reviewers. Note down potential risks to specific Editor branches if any._

- Complexity: 
- Halo Effect: 

### Comments to reviewers

_Please describe any additional information such as what to focus on, or historical info for the reviewers._

### Checklist

Before review:

- [ ] Changelog entry added.
    - Explains the change in `Changed`, `Fixed`, `Added` sections.
    - For API change contains an example snippet and/or migration example.
    - JIRA ticket linked, example ([case %<ID>%](https://issuetracker.unity3d.com/product/unity/issues/guid/<ID>)). If it is a private issue, just add the case ID without a link.
    - Jira port for the next release set as "Resolved".
- [ ] Tests added/changed, if applicable.
    - Functional tests `Area_CanDoX`, `Area_CanDoX_EvenIfYIsTheCase`, `Area_WhenIDoX_AndYHappens_ThisIsTheResult`.
    - Performance tests.
    - Integration tests.
- [ ] Docs for new/changed API's.
    - Xmldoc cross references are set correctly.
    - Added explanation how the API works.
    - Usage code examples added.
    - The manual is updated, if needed.

During merge:

- [ ] Commit message for squash-merge is prefixed with one of the list:
    - `NEW: ___`.
    - `FIX: ___`.
    - `DOCS: ___`.
    - `CHANGE: ___`.
    - `RELEASE: 1.1.0-preview.3`.

After merge:

- [ ] Create forward/backward port if needed. If you are blocked from creating a forward port now please add a task to ISX-1444.

2025-01-06 10:50 UTC, lyndon-unity requested changes

2025-01-06 10:50 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/InputSystemPluginControl.cs
> +            BuildTarget.PS5,
As mentioned in the U7 version of this PR, PS5 does need an NDA package too so not expecting this in the list.

2025-01-06 10:50 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/InputSystemPluginControl.cs
> +            foreach (var package in registeredPackages)
Need to check this takes into account the platforms required plugin. I'm concerned this would pass if p4 package installed and trying to use xbox.

2025-01-06 12:03 UTC, Pauliusd01 commented
~~Is this only when trying to build the actual player? Or should it also work for simply switching to the platform atm? Since I tried to switch to the xbox player and I'm able to run scenes in play mode without any of the warnings. One note, I have the platform installed but I do not have its GDK which might be the cause?~~ Never mind I switched scenes and suddenly it works, will mess around a bit more, might be a false alarm

2025-01-06 12:19 UTC, ritamerkl commented on Packages/com.unity.inputsystem/InputSystem/Editor/InputSystemPluginControl.cs
> +            foreach (var package in registeredPackages)
See [PR](https://github.cds.internal.unity3d.com/unity/neutron/pull/15552) for answer

2025-01-06 12:20 UTC, ritamerkl commented on Packages/com.unity.inputsystem/InputSystem/Editor/InputSystemPluginControl.cs
> +            BuildTarget.PS5,
Removed in [16479d4](https://github.com/Unity-Technologies/InputSystem/pull/2101/commits/16479d495bb2442ed489f6d06a2e32f8fbd45866)

2025-01-07 17:37 UTC, lyndon-unity requested changes

2025-01-07 17:37 UTC, lyndon-unity commented on Packages/com.unity.inputsystem/InputSystem/Editor/InputSystemPluginControl.cs
> +            m_pluginPackageRegistered = false;
This isn't granular enough. 
See https://github.cds.internal.unity3d.com/unity/neutron/pull/15552#pullrequestreview-889217

2025-01-08 12:43 UTC, ritamerkl commented on Packages/com.unity.inputsystem/InputSystem/Editor/InputSystemPluginControl.cs
> +            m_pluginPackageRegistered = false;
reworked to along what was discussed in our meeting. [15c4d2d](https://github.com/Unity-Technologies/InputSystem/pull/2101/commits/15c4d2d4fbc791a44b3c4619c5157693195700cb)

2025-01-09 13:55 UTC, Pauliusd01 approved these changes
LGTM here's a list of things I checked:

Opening a project with the platform already pre-selected - works as expected, error shows up
Switch to windows from a console platform - no error, as expected
Built on Xbox series x without the extension package - no error, but seems to be expected
Custom build profiles (with a console platform included) - error shows up without the extension as expected, cleared with the extension as expected
Xbox series X profile and Xbox extension installed - errors stop showing up as expected
Xbox profile and incorrect extension installed - still get the error as expected

I repeated the above with PS4, PS5 & Switch with only their Editor extensions built (_It just means I can I use the platform in Editor as normal but cannot build the player. So keep in mind that these platform players were not built_) and had the same expected results.

2025-01-09 19:10 UTC, lyndon-unity approved these changes
Thanks for the updates

2025-01-10 11:29 UTC, merged