updating demo files & scripts
Unity-Technologies/InputSystem pull request #223
Opened 2018-08-14 19:05 UTC by shawnmcclelland

Fixed a bug where looking around would cause the player transform to drift and added a new input action to handle physics based jumping.

2018-08-14 19:11 UTC, Rene-Damm requested changes

2018-08-14 19:11 UTC, Rene-Damm commented on Assets/Demo/SimpleController_UsingActions_InAsset.cs
> +	public void OnEnable()
Please run format.ps1/format.sh (found in repo root).

2018-08-14 19:11 UTC, Rene-Damm commented on Assets/Demo/SimpleController_UsingActions_InAsset.cs
> +        //transform.localEulerAngles = m_Rotation;
No commented out code without cause please. Either add comment why code is being kept or remove commented out code.

2018-08-14 19:11 UTC, Rene-Damm commented on Assets/Demo/SimpleController_UsingActions_InAsset.cs
> +    Rigidbody rb;
`m_RigidBody`.

2018-08-14 19:11 UTC, Rene-Damm commented on Assets/Demo/SimpleController_UsingActions_InAsset.cs
> +    private Vector3 m_Jump;
No need to have this one.

2018-08-14 19:11 UTC, Rene-Damm commented on Assets/Demo/SimpleController_UsingActions_InAsset.cs
> +        Quaternion localRotation = Quaternion.Euler(m_Rotation.x, m_Rotation.y, 0.0f);
Use var.

2018-08-14 19:11 UTC, Rene-Damm commented on Assets/Demo/SimpleController_UsingActions_InAsset.cs
> +            if(isGrounded == true)
`if (isGrounded)`

2018-08-14 19:19 UTC, shawnmcclelland commented on Assets/Demo/SimpleController_UsingActions_InAsset.cs
> +    private Vector3 m_Jump;
I could remove the private var and just have a var declaration inside of Awake(). m_Jump is re-used on 28 and 69 but that could get consolidated into a single var within the Awake loop I think.

2018-08-14 20:30 UTC, Rene-Damm commented on Assets/Demo/SimpleController_UsingActions_InAsset.cs
> +    private Vector3 m_Jump;
29 is just an assignment and 70 the only read it seems. Doesn't seem like it needs a var outside of the jump response code.

2018-08-15 22:43 UTC, merged

2018-08-24 19:32 UTC, Rene-Damm commented on Assets/Demo/SimpleController_UsingActions_InAsset.cs
> +        transform.rotation = localRotation;
Inverts Y.

2018-08-24 19:33 UTC, Rene-Damm commented on Assets/Demo/Demo.unity
> +GameObject:
Didn't catch this before. Shouldn't be in here.

2018-08-27 22:21 UTC, Rene-Damm commented on Assets/Demo/Demo.unity
> +Rigidbody:
Physics-based movement updates are now fighting direct transform updates.