First commit.  This fork adds QA tests...
Unity-Technologies/InputSystem pull request #28
Opened 2018-02-14 21:14 UTC by jackpr-unity

…, which right now consist of manual sanity check scenes meant to accelerate development.

- Keyboard and mouse scene
- Start at Xbox XInput scene.  Leaving this right now to pivot to touch testing.
- Updated .gitignore to include a Builds folder to enable building for tests.

2018-02-14 21:23 UTC, Rene-Damm requested changes

2018-02-14 21:23 UTC, Rene-Damm commented on Assets/QA/Tests/KeyboardMouseBasic/Scripts/ButtonStateHEX.cs
> +public class ButtonStateHEX : MonoBehaviour {
Please run Unity formatting tools on all C# code before committing. On OSX, run format.sh from the repo root. On Windows, run format.ps1 from there.

2018-02-14 21:23 UTC, Rene-Damm commented on Assets/QA/Tests/KeyboardMouseBasic/Scripts/ButtonStateHEX.cs
> +    Text OutputText;
Please conform to Unity code conventions for all C# code in the repo.

2018-02-14 21:23 UTC, Rene-Damm commented on Assets/QA/Tests/KeyboardMouseBasic/Scripts/MouseOutputs.cs
> +	}
Remove.

2018-02-14 21:23 UTC, Rene-Damm commented on Assets/QA/Tests/KeyboardMouseBasic/Scripts/KeyboardLastKey.cs
> +        //if (KB.)
Please clean up commented out code.

2018-02-15 00:26 UTC, jackpr-unity commented on Assets/QA/Tests/KeyboardMouseBasic/Scripts/ButtonStateHEX.cs
> +    Text OutputText;
Specifically, you are referring to the script name in this instance?

2018-02-15 03:22 UTC, Rene-Damm commented on Assets/QA/Tests/KeyboardMouseBasic/Scripts/ButtonStateHEX.cs
> +    Text OutputText;
To several places. Private property/field names need to be camelCase. Public ones m_PascalCase. Local variables camelCase. No _ prefixes on methods. Probably a couple more things.

2018-02-15 19:14 UTC, jackpr-unity commented
New commit that adheres to coding conventions.

2018-02-16 00:08 UTC, Rene-Damm commented
The files in .vs/ seem like accidental commits.

2018-02-16 00:10 UTC, Rene-Damm commented
Other than the .vs files, LGTM.

2018-02-16 00:33 UTC, jackpr-unity commented
Yep, didn't realize that I had to manually remove files that were already tracked after changing the .gitignore

2018-02-16 13:30 UTC, merged