Tweak OSX XInput layout
Unity-Technologies/InputSystem pull request #391
Opened 2019-01-25 20:39 UTC by douglas-piconi

The normalization values were screwing up the sticks, and the Up/Down had the wrong layout.

2019-01-30 02:23 UTC, Rene-Damm requested changes
Need test.

2019-02-06 19:19 UTC, douglas-piconi commented
@Rene-Damm tests added.

2019-02-10 00:42 UTC, Rene-Damm requested changes

2019-02-10 00:42 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/Tests/InputSystem/Plugins/XInputTests.cs
> +    }
Add right stick and trigger and use AssetButtonPress to check buttons.

2019-02-10 00:42 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/Tests/InputSystem/Plugins/XInputTests.cs
> +    }
Same here as with the test above.

2019-02-11 20:46 UTC, merged

2019-02-12 01:02 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/Tests/InputSystem/Plugins/XInputTests.cs
> +    }
Let's move the structs into the XInput plugin next to replace the current JSON layouts.