UI module improvements
Unity-Technologies/InputSystem pull request #566
Opened 2019-04-26 09:22 UTC by jechter

2019-04-29 10:20 UTC, Rene-Damm commented on Assets/Tests/InputSystem/CoreTests_Actions.cs
> +        var oldPressPoint = InputSystem.settings.defaultButtonPressPoint;
This is actually not necessary. A new settings object is created for every test and then thrown away.

2019-04-29 10:21 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/CHANGELOG.md
> +- Changed default button press point to 0.5.
The changelog entries ended up in the 0.2.8 section here. There's a new section for 0.3 (hopefully this time it'll be that) above.

2019-04-29 11:43 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/InputSystem/Plugins/UI/UIActionInputModuleEditor.cs
> +    internal class UIActionInputModuleEditor: UnityEditor.Editor
Can we have one of these for `StandaloneInputModule` to have a one-click switch over to this one?

2019-04-29 11:43 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/InputSystem/Plugins/UI/UIActionInputModuleEditor.cs
> +        private enum ActionReferenceType {
Please run format.sh before committing.

2019-04-29 11:44 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/InputSystem/Plugins/UI/UIActionInputModuleEditor.cs
> +        private string[] m_ActionNames = new[]
static?

2019-04-29 11:45 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/InputSystem/Plugins/UI/UIActionInputModuleEditor.cs
> +                const string buttonLabel = "Read Actions from Asset…";
"Link Actions from Asset..."?

2019-04-29 11:47 UTC, Rene-Damm commented on Packages/com.unity.inputsystem/InputSystem/Plugins/Users/InputUser.cs
> +                        Profiler.EndSample();
Good catch!

2019-04-29 11:47 UTC, Rene-Damm requested changes
Looks good to me. Couple small things.

2019-04-29 17:26 UTC, douglas-piconi approved these changes

2019-05-01 12:57 UTC, Rene-Damm approved these changes

2019-05-01 17:50 UTC, merged