Add Touch and Interactions
Unity-Technologies/InputSystem pull request #640
Opened 2019-05-22 22:19 UTC by JiaUnity

ADD: touch test
ADD: Interactions test
FIX: Some error due to new naming

2019-05-23 15:51 UTC, Rene-Damm approved these changes

2019-05-27 09:12 UTC, jechter requested changes

2019-05-27 09:12 UTC, jechter commented on Assets/QA/Input_Test/Scripts/Input/DualShockISX.cs
> +        //m_buttonAction.cancelled += callbackContext => OnControllerButtonPress(callbackContext.control as ButtonControl, isPS: true);
Why did you comment this (and the ones below) out? This API has been renamed to match the preferred US spelling, it should work using "canceled".

2019-05-27 09:12 UTC, jechter commented on Assets/QA/Input_Test/Scripts/Input/GamepadISX.cs
> +            //Debug.Log(dpadName);
Can we rather delete unneeded code then keep it around in comments?

2019-05-27 09:12 UTC, jechter commented on Assets/QA/Input_Test/Scripts/Input/XboxISX.cs
> +        //m_buttonAction.cancelled += callbackContext => OnControllerButtonPress(callbackContext.control as ButtonControl, isXbox: true);
Same here

2019-05-27 09:12 UTC, jechter commented on Assets/QA/Input_Test/Scripts/InputUIPicker.cs
> +        //switch (value)
can we delete this commented code?

2019-05-27 09:12 UTC, jechter commented on Assets/QA/Input_Test/Scripts/TouchDebugInfo.cs
> +        //// Add a new section
Same?

2019-06-19 00:43 UTC, closed without merging